# Generates src/generated/sheets.h: one struct initializer per sheet row.
import json,glob,os
S={os.path.basename(f)[:-5]:json.load(open(f)) for f in glob.glob('sheets/*.json')}
gc={r['name']:r['control_id'] for r in S['game_controls']['rows']}
inp=[r['action'] for r in S['inputs']['rows']]
o=["// GENERATED by tools/gen.py from sheets/*.json - edit the sheets, not this file.","#pragma once","#include <cstdint>",""]
o.append("enum class XrType{Pose,Float,Bool};")
o.append("struct InputRow{const char* action; XrType type; const char* pathPico4; const char* pathTouch; int control; int controlVehicle; float axisSign;};")
o.append("enum InputId{"+",".join("IN_"+a.upper() for a in inp)+",IN_COUNT};")
o.append("static const InputRow kInputs[IN_COUNT]={")
for r in S['inputs']['rows']:
  t={'pose':'XrType::Pose','float':'XrType::Float','bool':'XrType::Bool'}[r['xr_type']]
  c=gc.get(r['game_control'],-1); cv=gc.get(r['game_control_vehicle'],-1)
  sign=-1.0 if r['axis']=='-y' else 1.0
  o.append(f'  {{"{r["action"]}",{t},"{r["path_pico4"]}","{r["path_touch"]}",{c},{cv},{sign}f}},')
o.append("};")
o.append("struct ArmRow{const char* side; int ikIndex; InputId pose; int handBone; int blendIn; int blendOut; float maxReach; bool inVehicle;};")
o.append("static const ArmRow kArms[]={")
for r in S['arms']['rows']:
  o.append(f'  {{"{r["side"]}",{r["ik_index"]},IN_{r["pose_action"].upper()},{r["hand_bone_id"]},{r["blend_in_ms"]},{r["blend_out_ms"]},{r["max_reach_m"]}f,{str(r["active_in_vehicle"]).lower()}}},')
o.append("};")
o.append("struct NativeRow{const char* name; uint64_t hash;};")
nat=[r['name'] for r in S['natives']['rows']]
o.append("enum NativeId{"+",".join("N_"+n for n in nat)+",N_COUNT};")
o.append("static const NativeRow kNatives[N_COUNT]={")
for r in S['natives']['rows']:
  o.append(f'  {{"{r["name"]}",{r["hash"]}ull}},')
o.append("};")
st={r['name']:r['value'] for r in S['settings']['rows']}
o.append(f'static const char* kTargetBuild="{st["target_game_build"]}";')
o.append(f'static const float kWorldScale={st["world_scale"]}f, kAimRay={st["aim_ray_length"]}f, kTrigger={st["trigger_threshold"]}f;')
o.append(f'static const float kEyeHeight={st["eye_height"]}f;')
o.append(f'static const int kHeadBone={st["head_bone_id"]}; static const int kToggleVk=0x77; // {st["toggle_key"]}')
open('src/generated/sheets.h','w').write("\n".join(o)+"\n")
print("generated",len(o),"lines")
